"""Provenance banner + run ledger for analysis scripts.

The point is narrow: **the label on a number is generated by the code that made the
number**, not typed afterwards by the assistant. A script that uses this module cannot
print a table whose columns it has not defined, cannot pass off a mask as "stable"
without printing how many cells it actually keeps, and cannot introduce a parameter
nobody asked for without saying so in the output.

Usage::

    from trust.provenance import Run

    R = Run("does classifying both epochs with CSF close the gen1-gen2 gap?")
    zf_p  = R.input(f"{A.tile}/z_after.npy", role="gen2 ground = VENDOR class-2 per-cell median")
    csf_p = R.input(A.csf,                   role="gen2 ground = OUR CSF, same params as gen1")
    R.param("min_pts", A.min_pts, src="repo")
    R.param("slope_max", 90.0, src="MINE", why="wanted the whole patch; NOT the 12 deg repo default")
    ...
    R.mask("stable", stable, of=cover.size,
           defn="reference_cells(slope_max=90) -- geometric divide/curvature cuts only")
    R.column("dz_csf", "per-cell median of CSF ground h in the slope-normal frame, mm (= z_csf - z_after)")
    R.column("cells",  "count of reference cells in the stratum")
    R.banner()
    R.table(["stratum", "cells", "dz_csf"], rows)
    R.done()

`R.banner()` prints the header. `R.table()` refuses any column not passed to
`R.column()`. `R.done()` writes a JSON ledger under `.trust/runs/` that the Stop hook
reads, and prints the closing sentinel.

Self-test::

    python trust/provenance.py --selftest
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import os
import sys
import time

__all__ = ["Run", "BANNER_START", "BANNER_END"]

BANNER_START = "== PROVENANCE v1 =="
BANNER_END = "== END PROVENANCE =="
RUN_END = "== END RUN"

_SRC_OK = ("andy", "repo", "MINE")
_LEDGER_DIR = os.environ.get("TRUST_LEDGER_DIR", ".trust/runs")


def _digest(path: str) -> str:
    """Cheap content fingerprint: size + head/tail sha1. Big .npy files are GB-scale,
    so hashing whole files is not affordable per run; head+tail+size catches the
    substitutions we actually make (a different file, a regenerated file)."""
    h = hashlib.sha1()
    n = os.path.getsize(path)
    h.update(str(n).encode())
    with open(path, "rb") as f:
        h.update(f.read(1 << 20))
        if n > (2 << 20):
            f.seek(-(1 << 20), os.SEEK_END)
            h.update(f.read(1 << 20))
    return h.hexdigest()[:12]


def _human(n: int) -> str:
    for u in ("B", "K", "M", "G"):
        if n < 1024 or u == "G":
            return f"{n:.0f}{u}" if u == "B" else f"{n:.1f}{u}"
        n /= 1024.0


class ProvenanceError(RuntimeError):
    """Raised when a script tries to print something it has not defined."""


class Run:
    def __init__(self, question: str, *, argv=None):
        if not question or len(question.split()) < 3:
            raise ProvenanceError(
                "Run(question=...) must state, in a sentence, the question this run answers. "
                "If you cannot state it, do not run it."
            )
        self.question = question
        self.argv = list(argv if argv is not None else sys.argv)
        self.t0 = time.time()
        self.started = _dt.datetime.now().astimezone().isoformat(timespec="seconds")
        self.inputs: list[dict] = []
        self.params: list[dict] = []
        self.masks: list[dict] = []
        self.columns: dict[str, str] = {}
        self.notes: list[str] = []
        self._bannered = False
        self._done = False

    # ---------------------------------------------------------------- inputs
    def input(self, path: str, *, role: str) -> str:
        """Declare a real file this run reads. `role` says what the numbers in it MEAN.

        Returns the path, so it can wrap the read site: ``np.load(R.input(p, role=...))``.
        """
        if not role or len(role.split()) < 2:
            raise ProvenanceError(f"input({path!r}) needs role=... saying what it contains")
        ap = os.path.abspath(path)
        if not os.path.exists(ap):
            raise ProvenanceError(f"declared input does not exist: {ap}")
        st = os.stat(ap)
        self.inputs.append(dict(
            path=ap, role=role, bytes=st.st_size,
            mtime=_dt.datetime.fromtimestamp(st.st_mtime).isoformat(timespec="seconds"),
            digest=_digest(ap),
        ))
        return path

    # ---------------------------------------------------------------- params
    def param(self, name: str, value, *, src: str, why: str = "") -> object:
        """Declare a parameter and WHERE IT CAME FROM.

        src="andy"  -- the human specified this value, this session.
        src="repo"  -- it is the established default in the codebase / a prior decision.
        src="MINE"  -- the assistant chose it unasked. Requires `why`. Printed loudly and
                       recorded in the ledger; the Stop hook will not let the turn end
                       unless the reply discloses it.
        """
        if src not in _SRC_OK:
            raise ProvenanceError(f"param({name!r}) src must be one of {_SRC_OK}, got {src!r}")
        if src == "MINE" and len(why.split()) < 4:
            raise ProvenanceError(
                f"param({name!r}, src='MINE') needs why='...' -- a sentence on what you chose "
                f"and what it excludes. An unasked parameter that silently drops data is the "
                f"failure this module exists to stop."
            )
        self.params.append(dict(name=name, value=repr(value), src=src, why=why))
        return value

    # ----------------------------------------------------------------- masks
    def mask(self, name: str, m, *, defn: str, of: int | None = None):
        """Declare a boolean selection and print what it actually keeps.

        A name like "stable" or "core" is a claim about the population. This prints the
        claim's cost so the name can be checked against it.
        """
        import numpy as np  # local: keeps the module importable without numpy
        m = np.asarray(m)
        tot = int(of if of is not None else m.size)
        kept = int(m.sum()) if m.dtype == bool else int(np.isfinite(m).sum())
        if not defn or len(defn.split()) < 3:
            raise ProvenanceError(f"mask({name!r}) needs defn=... stating the cuts applied")
        frac = kept / tot if tot else float("nan")
        warn = ""
        if frac > 0.90:
            warn = ("  <-- KEEPS >90%: this is not a restrictive selection. "
                    "Do not call it a filtered population in prose.")
        self.masks.append(dict(name=name, kept=kept, total=tot, frac=frac, defn=defn, warn=bool(warn)))
        self._warns = getattr(self, "_warns", [])
        if warn:
            self._warns.append(f"mask {name!r} keeps {kept:,}/{tot:,} ({100*frac:.1f}%){warn}")
        return m

    def cuts(self, name: str, report: dict):
        """Record a criterion-by-criterion report, e.g. reference_cells()'s second return
        value. Discarding that report into `_` is how a 90%-of-the-tile mask got called
        "stable ground"."""
        self.notes.append(f"{name} cuts: " + ", ".join(f"{k}={v}" for k, v in report.items()))
        return report

    # --------------------------------------------------------------- columns
    def column(self, name: str, definition: str):
        if not definition or len(definition.split()) < 3:
            raise ProvenanceError(f"column({name!r}) needs a real definition, including UNITS")
        self.columns[name] = definition

    # ---------------------------------------------------------------- output
    def banner(self):
        w = print
        w(BANNER_START)
        w(f"question : {self.question}")
        w(f"run      : {self.started}   cwd={os.getcwd()}")
        w(f"argv     : {' '.join(self.argv)}")
        if os.environ.get("TRUST_GIT_REV"):
            w(f"git      : {os.environ['TRUST_GIT_REV']}")
        w("inputs   :")
        if not self.inputs:
            raise ProvenanceError("banner() with zero declared inputs -- declare them with R.input()")
        for i in self.inputs:
            w(f"  {i['path']}")
            w(f"      {_human(i['bytes'])}  mtime {i['mtime']}  sha1:{i['digest']}")
            w(f"      IS: {i['role']}")
        if self.params:
            w("params   :")
            for p in self.params:
                tag = {"andy": "[asked]", "repo": "[repo default]", "MINE": "[** MINE, UNASKED **]"}[p["src"]]
                w(f"  {p['name']} = {p['value']}  {tag}")
                if p["why"]:
                    w(f"      why: {p['why']}")
        if self.masks:
            w("selections:")
            for m in self.masks:
                w(f"  {m['name']}: keeps {m['kept']:,} of {m['total']:,} ({100*m['frac']:.1f}%)")
                w(f"      DEFINED AS: {m['defn']}")
        if self.columns:
            w("columns  :")
            for k, v in self.columns.items():
                w(f"  {k:<16s} {v}")
        for n in self.notes:
            w(f"note     : {n}")
        for s in getattr(self, "_warns", []):
            w(f"WARNING  : {s}")
        mine = [p for p in self.params if p["src"] == "MINE"]
        if mine:
            w("WARNING  : this run contains " + str(len(mine)) +
              " parameter(s) the assistant chose unasked: " + ", ".join(p["name"] for p in mine))
        w(BANNER_END)
        self._bannered = True

    def table(self, header: list[str], rows, *, fmt: str = ""):
        """Print a table. Every column name must have been defined via R.column()."""
        if not self._bannered:
            raise ProvenanceError("call R.banner() before printing any table")
        missing = [h for h in header if h not in self.columns]
        if missing:
            raise ProvenanceError(
                f"undefined column(s) {missing}: define each with R.column(name, 'what it is, with units') "
                f"before printing it. A column with no definition is a number with no label."
            )
        widths = [max(len(str(h)), *(len(str(r[i])) for r in rows)) if rows else len(str(h))
                  for i, h in enumerate(header)]
        print("  " + "  ".join(str(h).rjust(w) for h, w in zip(header, widths)))
        print("  " + "  ".join("-" * w for w in widths))
        for r in rows:
            print("  " + "  ".join(str(c).rjust(w) for c, w in zip(r, widths)))

    def done(self, *, headline: str = ""):
        """Close the run and write the ledger the Stop hook reads."""
        self._done = True
        rec = dict(
            question=self.question, started=self.started, argv=self.argv,
            seconds=round(time.time() - self.t0, 1), cwd=os.getcwd(),
            inputs=self.inputs, params=self.params, masks=self.masks,
            columns=self.columns, notes=self.notes, headline=headline,
            unasked=[p["name"] for p in self.params if p["src"] == "MINE"],
            session=os.environ.get("CLAUDE_SESSION_ID", ""),
        )
        os.makedirs(_LEDGER_DIR, exist_ok=True)
        stem = _dt.datetime.now().strftime("%Y%m%dT%H%M%S")
        path = os.path.join(_LEDGER_DIR, f"{stem}-{os.getpid()}.json")
        with open(path, "w") as f:
            json.dump(rec, f, indent=1)
        print(f"{RUN_END} ledger={path} =={'=' * 8}")
        return path


def _selftest():
    import numpy as np
    tmp = os.path.abspath("_trust_selftest.npy")
    np.save(tmp, np.arange(100.0))
    try:
        R = Run("does the provenance module refuse undefined columns?")
        R.input(tmp, role="synthetic array for the self-test")
        R.param("min_pts", 5, src="repo")
        R.param("slope_max", 90.0, src="MINE", why="whole patch instead of the 12 deg repo default")
        R.mask("stable", np.ones(100, bool), defn="no cuts at all, deliberately")
        R.column("stratum", "canopy-cover bin, dimensionless fraction")
        R.column("cells", "count of cells in the stratum")
        R.banner()
        R.table(["stratum", "cells"], [["open <0.05", 12], ["dense >0.35", 7]])
        for bad, fn in [
            ("undefined column", lambda: R.table(["stratum", "dz_csf"], [["a", 1]])),
            ("MINE without why", lambda: R.param("x", 1, src="MINE")),
            ("mask without defn", lambda: R.mask("core", np.ones(3, bool), defn="")),
            ("bad src", lambda: R.param("y", 1, src="guess")),
        ]:
            try:
                fn()
            except ProvenanceError as e:
                print(f"OK  refused: {bad}: {str(e)[:70]}...")
            else:
                print(f"FAIL did not refuse: {bad}")
                return 1
        R.done(headline="self-test complete")
    finally:
        os.remove(tmp)
    return 0


if __name__ == "__main__":
    sys.exit(_selftest() if "--selftest" in sys.argv else print(__doc__) or 0)
